### ISSUE TITLE
Падение при повторной попытке получить токен после отмены

### ISSUE THREAD

**Issue by ARRR42** [yandex-money/yandex-checkout-android-sdk#25]
Вызываем метод токенизации:

Intent intent = Checkout.createTokenizeIntent(getActivity(), paymentParameters);
            startActivityForResult(intent, Const.REQ_CODE_GOOGLE_PAY);

Сворачиваем окно GooglePay с выбором карты оплаты/аккаунта.

Снова вызываем метод токенизации. Получаем краш:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
        at android.support.v4.app.DialogFragment.show(DialogFragment.java:144)
        at ru.yandex.money.android.sdk.impl.CheckoutActivity.a(Unknown Source)
        at ru.yandex.money.android.sdk.impl.CheckoutActivity$a.invoke(Unknown Source)
        at ru.yandex.money.android.sdk.a.a$i.invoke(Unknown Source)
        at ru.yandex.money.android.sdk.impl.b.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

Xiaomi Redmi 3S, Android 6.0.1.

**Comment by drukarev** [comment]
Не смогли воспроизвести у себя.
Подскажите, пожалуйста:
1) Какая версия сдк используется
2) Как выглядит объект PaymentParameters, который прокидывается в метод createTokenizeIntent
3) Когда вызывается метод Checkout.createTokenizeIntent
4) Включена ли на телефоне настройка "Не сохранять действия" в настройках разработчика

Также поиск бага очень упростится, если удастся дать нам чистое приложение, на котором он всегда воспроизводится
