### ISSUE TITLE
Рандомное падение при токенизации

### ISSUE THREAD

**Issue by username4564** [yandex-money/yandex-checkout-android-sdk#28]
Стектрейс:
> java.util.ConcurrentModificationException: null
    at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:411)
    at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
    at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
    at ru.yandex.money.android.sdk.impl.d$ag.invoke
    at ru.yandex.money.android.sdk.a.k$a.invoke
    at ru.yandex.money.android.sdk.a.e.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:760)

Версия SDK 2.1.0 . До 2.2.0 обновились, но возможно эта проблема возникнет и в ней.
Воспроизводилось на 9 (SM-G950F) и 7 (Xiaomi Redmi Note 4) версии андроид.

**Comment by username4564** [comment]
Продолжает проявляться в версии 2.3.0 . Устройства Redmi S2, SM-A505FN, ANE-LX1

**Comment by Winner28** [comment]
Здравствуйте, проблема еще актуальна?

**Comment by username4564** [comment]
> Здравствуйте, проблема еще актуальна?

Нет, больше не встречается
