### ISSUE TITLE
Падение при попытке запустить 3DSecure 

### ISSUE THREAD

**Issue by AndreyBaranchikov** [yandex-money/yandex-checkout-android-sdk#4]
Лог:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.guidespot.client/ru.yandex.money.android.sdk.utils.CheckoutConfirmationActivity}: android.view.InflateException: Binary XML file line #38: Binary XML file line #38: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #38: Binary XML file line #38: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #38: Error inflating class fragment
     Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment ru.yandex.money.android.sdk.utils.WebViewFragment: make sure class name exists, is public, and has an empty constructor that is public
        at android.app.Fragment.instantiate(Fragment.java:527)
        at android.app.FragmentContainer.instantiate(FragmentContainer.java:49)
        at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3528)
        at android.app.FragmentController.onCreateView(FragmentController.java:98)
        at android.app.Activity.onCreateView(Activity.java:6219)
        at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:68)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at ru.yandex.money.android.sdk.utils.CheckoutConfirmationActivity.onCreate(Unknown Source:62)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-26 18:33:05.322 21022-21022/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "ru.yandex.money.android.sdk.utils.WebViewFragment" on path: DexPathList[[zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/base.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_resources_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Fragment.instantiate(Fragment.java:513)
        	... 29 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.guidespot.client-M2-I9B9yIa8qe2uGYgoGPQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
        at android.app.LoadedApk.getResources(LoadedApk.java:954)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        		... 6 more

**Comment by drukarev** [comment]
Fixed in 1.3.0.2
